[[customizations.user]]
name = "admin"
description = "Admin User"
key = "ssh-ed25519 REPLACE_WITH_YOUR_PUBLIC_KEY"
groups = ["wheel"]

[customizations.services]
enabled = [
  "sshd.service",
  "qemu-guest-agent.service",
  "cloud-init-local.service",
  "cloud-init.service",
  "cloud-config.service",
  "cloud-final.service",
]
